#   Ensure the Postgress gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: unicode
  database: medoo_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: medoo_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: medoo_prod
  pool: 5
  timeout: 5000